#!/usr/bin/env bash
# Music and generated sounds for the story films (not stored in git):
#  - Kevin MacLeod (incompetech.com), Creative Commons: By Attribution 4.0 — downloaded from incompetech.com
#  - synthesised effects/ambiences — generated by scripts/film/synth_se.py
set -euo pipefail
cd "$(dirname "$0")/../.."
PROD=${1:-production/nucleus-hq}
mkdir -p "$PROD/audio/bgm"
for t in "Late Night Radio" "Almost New" "Immersed" "Reawakening" "Man Down" "Danse Morialta"; do
  f="$PROD/audio/bgm/$t.mp3"; [ -f "$f" ] && continue
  u="https://incompetech.com/music/royalty-free/mp3-royaltyfree/$(python3 -c 'import sys,urllib.parse;print(urllib.parse.quote(sys.argv[1]))' "$t.mp3")"
  curl -sSL -m 300 -o "$f" "$u"
done
OUT="$PROD/audio/se/synth" python3 scripts/film/synth_se.py
